version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./src/:/var/www/rentalcarapi/
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    depends_on:
      - app

  app:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - ./src/:/var/www/rentalcarapi/
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: RentalCarDB
    ports:
      - '8854:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/